dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: plastocartheartbeat
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.5
